### ISSUE TITLE
Parse without render?

### ISSUE THREAD

**Issue by czukowski** [cebe/markdown#125] opened 2016-09-14 15:32 UTC
My use case is extracting links (or in general, any required content) from a markdown file. I could achieve it except for the inline elements, because I cannot call `prepareMarkers` method since it's private.

I can see two possible solutions:

1. Make `prepareMarkers` protected and leave the rest to those who wish to dig in it (eg myself).
2. Keep `prepareMarkers` private, but create a separate method for parsing without rendering. This could also help resolve the current code duplication between `parse` and `parseParagraph` method. The question is whether to make it public (change public API) or protected (no change): the data coming from `parseBlocks` and `parseInline` methods are highly implementation-specific and probably would make sense only for parser extensions.

I may be able to provide a pull request for this.

**Comment by cebe** [comment] 2016-09-14 20:33
> because I cannot call prepareMarkers method since it's private.

`prepareMarkers()` is protected: https://github.com/cebe/markdown/blob/04bfcaa26356cf86c6c4a2420eb95857a86e03ab/Parser.php#L294 ?

**Comment by cebe** [comment] 2016-09-14 20:34
duplicate of #113

**Closed by cebe** 2016-09-14 20:34 UTC

**Comment by cebe** [comment] 2016-09-14 20:41
released a new version that includes these changes: https://github.com/cebe/markdown/releases/tag/1.1.1

**Comment by czukowski** [comment] 2016-09-15 09:57
Thank you!
