### ISSUE TITLE
composer up not working for yii2

### ISSUE THREAD

**Issue by loveorigami** [cebe/markdown#154] opened 2018-03-16 12:54 UTC
After ```composer up --prefer-dist``` I get

```
Problem 1
      - Installation request for yiisoft/yii2 2.0.14.2 -> satisfiable by yiisoft/yii2[2.0.14.2].
      - yiisoft/yii2 2.0.14.2 requires cebe/markdown ~1.0.0 | ~1.1.0 -> no matching package found.
```

This problem I get after your new release 1.2. https://github.com/cebe/markdown/releases/tag/1.2.0

3 days ago ```composer up``` worked fine.

**Comment by samdark** [comment] 2018-03-16 14:52
https://packagist.org/packages/cebe/markdown#1.1.0 Tags are in place. Have you updated composer itself recently?

**Comment by cebe** [comment] 2018-03-18 06:43
Can you show your composer.json file?

**Comment by loveorigami** [comment] 2018-03-19 07:35
Yes, I also see this tag. But it not working.
Today I also did ``` composer self-up```

My composer file

```
{
  "name": "yiisoft/yii2-app-advanced",
  "description": "Yii 2 Advanced Project Template",
  "keywords": [
    "yii2",
    "framework",
    "advanced",
    "project template"
  ],
  "homepage": "http://www.yiiframework.com/",
  "type": "project",
  "license": "BSD-3-Clause",
  "support": {
    "issues": "https://github.com/yiisoft/yii2/issues?state=open",
    "forum": "http://www.yiiframework.com/forum/",
    "wiki": "http://www.yiiframework.com/wiki/",
    "irc": "irc://irc.freenode.net/yii",
    "source": "https://github.com/yiisoft/yii2"
  },
  "repositories": [
    {
      "type": "composer",
      "url": "https://asset-packagist.org"
    }
  ],
  "minimum-stability": "dev",
  "require": {
    "php": ">=7.0",
    "yiisoft/yii2": "2.0.14.2",
    "yiisoft/yii2-bootstrap": "~2.0.6",
    "yiisoft/yii2-swiftmailer": "~2.1.0",
    "yiisoft/yii2-authclient": "~2.1.0",
    "yiisoft/yii2-jui": "~2.0.0",
    "hiqdev/composer-config-plugin": "*",

    "samdark/hydrator": "~1.0.0",
    "samdark/yii2-webshell": "~2.0",

    "loveorigami/lo-core": "*",
    "bower-asset/flatpickr": "3.0.*"
  },
  "require-dev": {
    "yiisoft/yii2-debug": "~2.0.0",
    "yiisoft/yii2-gii": "~2.0.0",
    "yiisoft/yii2-faker": "~2.0.0"
  },
  "config": {
    "process-timeout": 1800
  },
  "scripts": {
    "post-install-cmd": "php init --env=Development --overwrite=n"
  }
}

```

**Comment by loveorigami** [comment] 2018-03-19 07:38
![composer](https://user-images.githubusercontent.com/98164/37583250-b30117c2-2b61-11e8-9b5a-2cf2903bfdc1.jpg)

**Comment by loveorigami** [comment] 2018-03-19 07:46
... and if i deleted
```

    {
      "type": "composer",
      "url": "https://asset-packagist.org"
    },
```
result is same

**Comment by loveorigami** [comment] 2018-03-19 09:54
for "yiisoft/yii2": "2.0.*" update is good, because fixed in https://github.com/yiisoft/yii2/issues/15899

**Comment by samdark** [comment] 2018-03-19 13:04
Reported to Jordi and Nils via email.

**Comment by SilverFire** [comment] 2018-03-19 13:29
For now drop `vendor` and run `composer update`

**Comment by cebe** [comment] 2018-03-19 13:44
I suspect the following to be the problem:

1. you have composer.json with `"yiisoft/yii2": "2.0.14.2",` which depends on [`"cebe/markdown": "~1.0.0 | ~1.1.0"`](https://github.com/yiisoft/yii2-framework/blob/ef74f3783e964cea477f06e6d6ce209df1f37881/composer.json#L72).
2. before I released 1.2.0, there was a `branch-alias` in composer.json of [cebe/markdown: `"dev-master": "1.1.x-dev"`](https://github.com/cebe/markdown/blob/1.2.0/composer.json#L39). 
  So if you have `minimum-stabilty: dev` as I see in your composer.json above, you get something installed that is now released as 1.2.0.
3. now after 1.2.0 release, I [changed the branch alias to `1.2.x-dev`](https://github.com/cebe/markdown/commit/209cc2cffc7f94f3e5ad8c3044c116a86623a4da)
4. a composer update which was at the 1.1.x-dev branch now wants to upgrade but has the constraint to stay in the `"~1.0.0 | ~1.1.0"` constraint given by Yii. It can not upgrade to 1.2.0, but needs to downgrade from 1.1.x-dev to some stable 1.1.x version, but that seems to fail.

Not sure if what I described above is the cause of the problem but I think it is very likely.

**Comment by samdark** [comment] 2018-03-19 13:48
Nils confirmed that packagist/composer are OK i.e. UI displays correct data.

**Comment by loveorigami** [comment] 2018-03-20 07:26
@cebe Many Thanks!

**Comment by tnguyen444** [comment] 2018-08-12 00:14
Hi is there an actual solution to this problem?  I have having the same error message.

**Comment by cebe** [comment] 2018-08-13 08:10
@tnguyen444 are you able to reproduce the problem in a minimal setup of composer? Would be worth reporting that as a bug.

**Comment by cebe** [comment] 2018-08-13 09:33
I tried to rebuild this problem with a minmal set of packages but I am unable to reproduce it with composer 1.7.1, maybe it has been resolved already? I found something else that is weird when using `minimum-stability: dev`, reported that in https://github.com/composer/composer/issues/7544

**Comment by cebe** [comment] 2018-08-13 09:48
could be related to https://github.com/composer/composer/issues/7329

**Closed** 2020-10-07 10:00 UTC
