### ISSUE TITLE
PHP Notice:  Uninitialized string offset: 0 in /.../inline/LinkTrait.php on line 249

### ISSUE THREAD

**Issue by svivian** [cebe/markdown#126] opened 2016-09-20 15:24 UTC
I'm getting this error on certain pages of my forum. Took a bit of testing but I found that it's due to the `identityReference` method being called with a blank string (then `$line[0]` gives the notice). Strangely this only happens on my live site (PHP 7) and not on localhost (PHP 5.6). On localhost, boolean `false` is passed into the function instead (and `$live[0]` doesn't produce a notice for some reason).

The specific Markdown that causes the problem is:

```
- A

 - B



 - C



 - D
```

Hopefully Github preserves the spaces but to be clear, there is a space before the dash on list items B, C, D. And between B/C and C/D there is a line with 3 spaces. (Yes I know it crappy Markdown but this is what a user typed on my forum...)

Anyway hope this helps find the source of the error. Presumably the easiest fix is (a) to make sure that `$line` is always passed as a string into the function, and (b) if it's empty, don't try to read `$line[0]`.

**Comment by cebe** [comment] 2016-09-21 09:30
Thanks for reporting this. Of course the parser should not crash regardless how "crappy" the markdown is ;)
I am however not able to reproduce the issue. Can you put the markdown that crashes the parser into http://markdown.cebe.cc/try and send me the link?

**Comment by svivian** [comment] 2016-09-21 13:34
Here is the link: http://markdown.cebe.cc/try?flavor=default&text=-+A%0D%0A%0D%0A+-+B%0D%0A%0D%0A+++%0D%0A%0D%0A+-+C%0D%0A%0D%0A+++%0D%0A%0D%0A+-+D

But no notice is shown. What version of PHP is being used on that site? As I said it only gives the notice on PHP 7.

**Comment by remyvhw** [comment] 2017-02-01 20:56
Same issue here; with PHP 7.1.

`- Hello, world!

  

This is zonda!`
with two spaces between two \n doesn't work, while, 
`- Hello, world!



This is zonda!`
does.

**Comment by stefanschindler** [comment] 2017-07-03 12:44
Experienced exactly the same bug as @remyvhw  with PHP 7.0.18:

Empty lines with blank characters throw an exception:

```
- List...

  

Will throw Exception
```

```
- List...



Doesn't throw Exception
```

Here is the relevant part of the Stack Trace:

```
[2017-07-03 12:34:36] production.ERROR: ErrorException: Uninitialized string offset: 0 in /var/www/vhosts/domain/releases/version__160/vendor/cebe/markdown/inline/LinkTrait.php:249
Stack trace:
#0 /var/www/vhosts/domain/releases/version__160/vendor/cebe/markdown/inline/LinkTrait.php(249): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Uninitialized s...', '/var/www/vhosts...', 249, Array)
#1 /var/www/vhosts/domain/releases/version__160/vendor/cebe/markdown/block/ListTrait.php(125): cebe\markdown\Markdown->identifyReference('')
#2 /var/www/vhosts/domain/releases/version__160/vendor/cebe/markdown/block/ListTrait.php(68): cebe\markdown\Markdown->consumeList(Array, 18, Array, 'ul')
#3 /var/www/vhosts/domain/releases/version__160/vendor/cebe/markdown/Parser.php(195): cebe\markdown\Markdown->consumeBUl(Array, 18)
#4 /var/www/vhosts/domain/releases/version__160/vendor/cebe/markdown/Parser.php(170): cebe\markdown\Parser->parseBlock(Array, 18)
#5 /var/www/vhosts/domain/releases/version__160/vendor/cebe/markdown/Parser.php(60): cebe\markdown\Parser->parseBlocks(Array)
```

**Comment by cebe** [comment] 2017-07-03 13:09
Thank you all for reporting this. I was able to reproduce the issue now. Committed a fix.

**Closed** 2017-07-03 13:08 UTC
Labels: bug
