### ISSUE TITLE
Expansion

### ISSUE THREAD

**Issue by dlmwolf** [cebe/markdown#108] opened 2015-08-06 08:25 UTC
I want to add a Expansion,but i don't know how to do this.
So submit this issues.
I want to the `[ ]` to `<input type="checkbox">`.
and the  `[x]` to `<input type="checkbox" checked="checked">`.
Thanks for look that.

**Comment by cebe** [comment] 2015-08-06 12:09
duplicate of #29

**Closed by cebe** 2015-08-06 12:09 UTC

**Comment by dlmwolf** [comment] 2015-08-12 02:23
@cebe Thank you

**Comment by cebe** [comment] 2015-08-12 11:26
you have to change the parsing of list elements: https://github.com/cebe/markdown/blob/master/block/ListTrait.php#L71
